### ISSUE TITLE
Legion cross-compilation error: `SIGILL, Illegal instruction`

### ISSUE THREAD

**Issue by goliaro** [flexflow/FlexFlow#460]
When cross-compiling Legion using [this workflow](https://github.com/flexflow/flexflow-third-party/blob/master/.github/workflows/build.yml) in order to make the FlexFlow builds faster (as introduced by PR #400), we sometimes incur in the following error when running `flexflow_python` after building with a pre-built Legion library (`FF_USE_PREBUILT_LEGION=ON`):

```bash
root@eb4f2fb7dc5e:~# flexflow_python
Illegal instruction (core dumped)
```

Upon further inspection (running `flexflow_python` under GDB), we can see that this error comes from the Realm cross-compilation:

```bash
root@f560dd9f5aed:/usr/FlexFlow# gdb flexflow_python
GNU gdb (Ubuntu 8.1.1-0ubuntu1) 8.1.1
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from flexflow_python...(no debugging symbols found)...done.
(gdb) run
Starting program: /usr/local/bin/flexflow_python 
warning: Error disabling address space randomization: Operation not permitted
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".

Program received signal SIGILL, Illegal instruction.
0x00007f6ecbb69f95 in Realm::CodeDescriptor::CodeDescriptor(Realm::Type const&) () from /usr/local/lib/librealm.so.1
```

To fix this bug, we need to figure out how to properly cross-compile Legion. 

<details>
<summary>Additional info:</summary>
<br>

The pre-compiled Legion library was built in a Github runner. Both the runner and the target machine run ubuntu 20.04 with a x86_64 architecture. The target machine compiled FlexFlow with `FF_USE_AVX2=OFF`
Results of running `lscpu | grep avx` on both on the Github runner which produced the pre-compiled Legion/Realm library, as well as the target architecture:

**Git runner:**
```
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc rep_good nopl xtopology cpuid pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 movbe popcnt aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch invpcid_single pti fsgsbase bmi1 hle avx2 smep bmi2 erms invpcid rtm avx512f avx512dq rdseed adx smap clflushopt avx512cd avx512bw avx512vl xsaveopt xsavec xsaves md_clear
```
**Target machine**
```
Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf tsc_known_freq pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb cat_l2 invpcid_single cdp_l2 ssbd ibrs ibpb stibp ibrs_enhanced tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid rdt_a rdseed adx smap clflushopt clwb intel_pt sha_ni xsaveopt xsavec xgetbv1 xsaves split_lock_detect avx_vnni dtherm ida arat pln pts hwp hwp_notify hwp_act_window hwp_epp hwp_pkg_req umip pku ospke waitpkg gfni vaes vpclmulqdq tme rdpid movdiri movdir64b fsrm md_clear serialize pconfig arch_lbr flush_l1d arch_capabilities
```
</details>
